### ISSUE TITLE
Explain why ultra low latency is <1 second 

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#100]
From @evyncke 
While I am not an expert, I am surprised by the acceptable latency numbers, I would have written 100 msec for videoconference and "couple of seconds" for streaming live events. Video streaming (netflix like) is indeed several seconds. But, I am trusting the authors on their statement. Section 4.2 explains a little more those numbers so a forward reference to section 4 would be beneficial.

**Comment by GrumpyOldTroll** [comment]
On-list discussion so far concluded that we are best off leaving it alone, with no dissent yet:
https://mailarchive.ietf.org/arch/msg/mops/eX2YT2-ynEbheZBOeyGnH1vZGM0/

**Comment by SpencerDawkins** [comment]
I've raised this issue a few times, but suspect that the right answer is to 

- Don't change any of the numbers in this document,
- Recognize that latency goals are falling year by year, and 
- Wait until we better understand the thinking in MOQ discussions about the latency requirements for live media streaming and other forms of media handling to revisit this

The likely improvements from continued discussions about latency categories aren't worth holding up this document.

**Comment by evyncke** [comment]
> * Recognize that latency goals are falling year by year, and

Up to the authors, really, but suggest to add some text about those numbers are in flux ?

**Comment by GrumpyOldTroll** [comment]
Yeah, that sounds like a good idea.  Some clarifying context in the section 4 header where these numbers appear might help avoid some confusion.

**Comment by SpencerDawkins** [comment]
@GrumpyOldTroll - that sounds like a win to me. 

My goal was to **NOT** say something like "these numbers are old and inaccurate, so good luck!"

**Comment by SpencerDawkins** [comment]
We agree with the suggestion for forward reference to Section 4.
