### ISSUE TITLE
Mention HTTP by middlebox as an advantage

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#102]
From @evyncke 
In the advantage of HTTP, would the acceptance of HTTP by middle box be another plus ?

**Comment by SpencerDawkins** [comment]
W could reasonably mention the deployed HTTP infrastructure

**Comment by GrumpyOldTroll** [comment]
We do have this in the list of positives, I think this covers it?

- "HTTP can make use of already-deployed caching infrastructure."

https://htmlpreview.github.io/?https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/blob/gh-pages/draft-ietf-mops-streaming-opcons.html#section-2

Should we ask Eric if there's another kind of middle box he wants included here that's not covered by "the caching infrastructure"?

**Comment by SpencerDawkins** [comment]
Asking Eric now ... @evyncke

**Comment by evyncke** [comment]
> Should we ask Eric if there's another kind of middle box he wants included here that's not covered by "the caching infrastructure"?

Never hesitate to ask of course ;-)

And, yes I was mainly hinting at the CDN infrastructure.

**Comment by SpencerDawkins** [comment]
@GrumpyOldTroll - I THINK I wrote the text in Section 2, and I'm not sure I was thinking specifically about CDNs in that text. 

What I'm thinking, is for me to take a quick spin through the draft looking at our references to middleboxes, caches, CDNs, and anything else that's in the draft now, and making sure it's coherent. Right now, I'm not sure it does, and we may say things that would apply to more than one of those, but that aren't consistent. 

Does that make sense?

**Comment by SpencerDawkins** [comment]
Overarching term is "caching infrastructure", add "such as".
