### ISSUE TITLE
Check terminology for "server-player systems"

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#106]
From @evyncke 
Unsure whether "server-player systems" is well understood by the readers.

Nit: "some metric monitored by the client" should the plural form be used ?

**Comment by acbegen** [comment]
I dont think we made the exercise of going thru all the mixed-up terms like clients vs. players in the text. One simple solution is to do the following:
- (streaming) client: the part of the (media) player that deals with the transmission/reception and buffer related matters.
- (media) player: on top of the streaming client, this includes the media decoders, UI, user controls, DRM, authentication modules, etc.

**Comment by SpencerDawkins** [comment]
"many systems" -
