### ISSUE TITLE
Clarify networking issues in 5.5 

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#107]
From @evyncke 
Same comment as for section 1, "networking issues" actually means something broader than the plain layer-3. Suggest introducing the shortcut in the terminology part of section 1, e.g., "this document uses the wording networking issues to represent the conjunction of IP and transport layers" ?

**Comment by SpencerDawkins** [comment]
Hi, @@evyncke, I thought this might be a quick addition of an umbrella definition of "networking" to include transport protocols, but a significant chunk of the text was distinguishing between network and transport protocols, so I added "and transport protocols" to the few occurrences of "networking" that were intended to include both.

**Comment by evyncke** [comment]
Thank you, @SpencerDawkins , this is more work for the authors but less ambiguous for the readers.
