### ISSUE TITLE
App level encryption is not addressed. 

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#111]
From @evyncke

Based on the title it is unclear whether this section also covers "app layer encryption", I guess no but this should be made clear (perhaps high in section 7 by stating that this doc does not cover app layer encryption).

**Comment by SpencerDawkins** [comment]
This paragraph 

> In this document, we will focus on media encrypted at the transport layer, whether encrypted "hop-by-hop" or "end-to-end". Because media encrypted at the application layer will only be processed by application-level entities, this encryption does not have transport-layer implications.

appears later in the document - I can move this up under the bullet points and make that clearer.

**Comment by SpencerDawkins** [comment]
Fixed as in my previous comment.

**Comment by evyncke** [comment]
BTW, unsure how the authors want me to mark "I have read the change and I like it" ? Currently, simply using a "thum up" emoticon on the solution comment.

Let me know if you prefer another marking.
