### ISSUE TITLE
Applicability of pre-placement and caching

### ISSUE THREAD

**Issue by GrumpyOldTroll** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#13]
Pulling the TBD out of the draft text and capturing it here instead.

Suggestion from mic at IETF 106 (Dave Oran + Glenn Deen responding):
Pre-placement for many use cases is useful--distinguish between live vs. cacheable.  "People assume high-demand == live, but not always true" with popular netflix example.  Pre-placement in caches can ameliorate high-bandwidth needs without having to use e.g. multicast.  Explain where it's applicable and not, and what the constraints are.
https://www.youtube.com/watch?v=4_k340xT2jM&t=14m15s

(This probably goes in the caching section as that's written.)

**Comment by GrumpyOldTroll** [comment]
+Glenn's comment: also capture latency constraints as a usability/qos part for live+popular vs. pre-recorded and expected-popular.

**Comment by SpencerDawkins** [comment]
I would like to think that PR 30 is a start here ...

**Comment by SpencerDawkins** [comment]
#30 was merged, but this issue wasn't closed. Closing now ...
