### ISSUE TITLE
Latency categories are coming up mildly controversial in wider review

### ISSUE THREAD

**Issue by GrumpyOldTroll** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#130]
For example, see:
 - https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/pull/129
 - https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/issues/100

It might be worth thinking a bit about whether there's any worthwhile improvements we can make here before it's too late.  As much as I don't want to chase a moving target, I also don't want to ship something that lacks consensus.

**Comment by acbegen** [comment]
I think chances for a consensus are more likely if we keep it simple, see my suggested text [here](https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/pull/129/files#r863222249).

**Comment by GrumpyOldTroll** [comment]
I'll integrate ali's comments, turn this into a new pr, and pull it:
https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/commit/8942fbb771636194ab42bd29c15e65cb9e05a34b

**Comment by GrumpyOldTroll** [comment]
One more thing we should perhaps integrate to help with this is to clarify that "Ultra Low Latency" is an industry term of art in segmented streaming video delivery, and that's basically where this category's name came from.

([There's](https://www.ibc.org/thought-leadership/ultra-low-latency-streaming-with-cmaf/6312.article) [many](https://rtmp-server.com/the-holy-grail-quest-for-ultra-low-latency-streaming-using-cmaf/) [example](https://www.youtube.com/watch?v=Obq_1LuScvM) [usages](https://medium.com/exmachinagroup/the-ultra-low-latency-video-streaming-roadmap-from-webrtc-to-cmaf-5b0d8b4ceec2) [posted](https://antmedia.io/webrtc-transforms-live-streaming/).)

**Comment by GrumpyOldTroll** [comment]
PS: Came up again from @michael-scharf 's review (https://mailarchive.ietf.org/arch/msg/mops/eGGPYW2vytPsLwRBlJ38MezPFh0/)

Section 4.  Latency Considerations and Section 4.1.  Ultra Low-Latency

I am surprised by the definition "ultra low-latency (less than 1 second)", as
well as some of the other numbers. For other real-time communication use cases,
"ultra low-latency" would probably imply a latency requirement of the order of
*one millisecond*. For instance, isochronous traffic for motion control in
industrial networks may require a latency of 1 ms, and such "ultra-low latency"
requirements are discussed elsewhere, e.g., in the DetNet WG. The terminology
in this section should be better explained to readers dealing with networked
systems with much harder latency requirements. And a reference should be added
for these definitions in the context of video streaming.

**Comment by GrumpyOldTroll** [comment]
closed via https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/pull/136
