### ISSUE TITLE
Improve accuracy of description of DNS operation over UDP

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#133]
From @tfpauly:

- In Section 6.1 (on UDP), DNS queries are described as follows: "DNS, which is
often used to send a single-packet request to look up the IP address for a DNS
name, and return a single-packet response containing the IP address." I'm not
sure how valuable this example is for explaining UDP, but if it is kept, please
say that *multiple* packets are sent to get *multiple* addresses. With IPv6 and
IPv4, clients query for both A and AAAA records, and handle multiple addresses,
especially for IPv6.

**Comment by SpencerDawkins** [comment]
FWIW, I understand why you're saying this. My point (and I wrote this) was to explain why it we've used DNS over UDP for decades without worrying about congestive collapse, but we've used other protocols over TCP because we were worried. 

I can certainly explain that more correctly, as you propose. And thanks for pushing back.

**Comment by SpencerDawkins** [comment]
Hi, @tfpauly, especially after @michael-scharf suggesting in his TSVART review that I don't need to talk about history, removing this text completely was a perfectly reasonable resolution for your issue!

**Comment by tfpauly** [comment]
Sounds good
