### ISSUE TITLE
Comparison between UDP and TCP isn't quite right - should be between applications over UDP and over TCP

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#134]
From @tfpauly

- As a bit of transport commentary, I don't find the setup of Section 6
compelling. While UDP is a transport in a technical sense, for the purpose of
media, it is almost always a layer upon which the protocol doing the congestion
control work runs. To that end, QUIC is just another more standardized case of
this, just like SCTP over UDP. Rather than talking about "UDP's behavior" vs
"TCP's behavior", I suggest talking about how applications over UDP for media
behave vs applications over TCP for media behave.

**Comment by SpencerDawkins** [comment]
@tfpauly - I need to look at this more closely. I understand your point about UDP, but (because UDP is not a real transport layer, while TCP and QUIC are), I suspect (without looking closely yet) I'm going to be making sure that I explain this more clearly, without trying to explain the behavior(s) of applications running over TCP and QUIC. 

As an aside, I'm trying to make this clearer in drafts I'm targeting forwards Media Over QUIC/MOQ, so I actually DO believe you ... 

Please await results.

**Comment by GrumpyOldTroll** [comment]
A +1 from @michael-scharf 's review (https://mailarchive.ietf.org/arch/msg/mops/eGGPYW2vytPsLwRBlJ38MezPFh0/):

Section 6.  Evolution of Transport Protocols and Transport Protocol Behaviors

I really wonder whether UDP vs. TCP vs. QUIC is actually the relevant
distinction. What may actually matter are the transport services provided by
the protocol stack (e.g., RFC 8095). I fully agree to a related comment in the
INTDIR review.

**Comment by SpencerDawkins** [comment]
After looking at this issue. I agree with both @tfpauly and @michael-scharf that the emphasis should be on the interaction between (see new section describing this) media transport protocols and the transport services provided by underlying transport protocols.

I'm moving the formerly-UDP section below the formerly-TCP section, because it's easier to describe what UDP is NOT doing after describing what TCP IS doing. I'm also moving one paragraph into the formerly-TCP section from Section 6, because it is specific to ABR strategies that assume a reliable transport. 

More news to come, when I create a PR for this issue ...

**Comment by SpencerDawkins** [comment]
We think #169  is now mergrable.
