### ISSUE TITLE
assuming relatively static path properties

### ISSUE THREAD

**Issue by GrumpyOldTroll** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#137]
From @michael-scharf (https://mailarchive.ietf.org/arch/msg/mops/eGGPYW2vytPsLwRBlJ38MezPFh0/)

* Section 3.2.1.  Recognizing Changes from an Expected Baseline

This section apparently assumes relatively static path properties, e.g., fixed
network connectivity. It would be more useful to analyze the impact of Wifi and
4G/5G networks in one place. Some of this follows later in sections 3.2.1 and
5.5.3. Yet, the split between these three sections is unclear. Having a
discussion about today's Internet path characteristics and the dynamics at one
place could be more useful.

**Comment by SpencerDawkins** [comment]
Related to #142
