### ISSUE TITLE
References with measurements about HOL-blocking

### ISSUE THREAD

**Issue by GrumpyOldTroll** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#141]
From @michael-scharf 's review (https://mailarchive.ietf.org/arch/msg/mops/eGGPYW2vytPsLwRBlJ38MezPFh0/)

Section 5.5.2 Head-of-Line Blocking

If Head-of-Line Blocking is indeed a relevant operational problem, it would be
useful to add a corresponding reference (e.g., with measurements).

**Comment by GrumpyOldTroll** [comment]
Also mentioned in section 6.3 about QUIC.

**Comment by SpencerDawkins** [comment]
@michael-scharf 'said 

> As already noted, the discussion about head-of-line-blocking would really
benefit from backing by a reference.

**Comment by acbegen** [comment]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/18185643/170566780-64ba6eba-0c57-422c-8889-d1c2b9531df1.png">
Fig. 1 from https://ieeexplore.ieee.org/document/9154522

**Comment by GrumpyOldTroll** [comment]
Change the section title for 5.5.2: it's not really about head-of-line blocking specifically, it's about a noisy goodput signal when measuring data received at the application layer, which requires appropriate smoothing in the player's bitrate detection algorithm.

**Comment by SpencerDawkins** [comment]
The text in 6.3 isn't about head-of-line blocking, either.

**Comment by SpencerDawkins** [comment]
Discussion on editor conference call: 
- we really like the diagram Ali provided ...

**Comment by SpencerDawkins** [comment]
closed by #184
