### ISSUE TITLE
Wireless considerations prevalence and location in doc

### ISSUE THREAD

**Issue by GrumpyOldTroll** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#142]
from @michael-scharf 's review (https://mailarchive.ietf.org/arch/msg/mops/eGGPYW2vytPsLwRBlJ38MezPFh0/)

Section 5.5.3.  Wide and Rapid Variation in Path Capacity

The statement "As many end devices have moved to wireless connectivity for the
final hop (Wi-Fi, 5G, or LTE), new problems in bandwidth detction have emerged
from radio interference and signal strength effects." could be moved to earlier
parts of the document. Quite a bit of new computers apparently only have Wifi
connectivity and no Ethernet port, i.e., Wifi may just be their default. Also,
wireless may not only be used on the last hop, for instance in meshed setups.
This may make the problem even harder.

**Comment by SpencerDawkins** [comment]
This comment helpfully points out the changing network architecture (a LOT of wireless), and we should be clearer about what we're talking about in Section 3.2 (our mental was mostly wired) and in 5.5.3 (where we focused on wireless). 

This material should go in Section 3.2, and should be referenced in 5.5.3..
