### ISSUE TITLE
Roman Danyliw's Ballot Comments - Discuss

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#152]
From @rdanyliw

> ** Section 5.4.
> 
>    Ads may be inserted either with Client Side Ad Insertion (CSAI) or
>    Server Side Ad Insertion (SSAI).  In CSAI, the ABR manifest will
>    generally include links to an external ad server for some segments of
>    the media stream, while in SSAI the server will remain the same
>    during advertisements, but will include media segments that contain
>    the advertising.  In SSAI, the media segments may or may not be
>    sourced from an external ad server like with CSAI.
> 
>          …
> 
>    As a
>    mitigation for concerns driven by those incidents, some SSPs have
>    required the use of players with features like reporting of ad
>    delivery, or providing information that can be used for user
>    tracking.  Some of these and other measures have raised privacy
>    concerns for end users.
> 
> Thanks for starting the discussion about privacy.  The framing doesn’t seem
> completely accurate.  Whether there is ad fraud or not, user data of some kind
> is being sent off to ad exchanges (it’s the basis of the bidding process), and
> network level tracking is being facilitated through connects to CSAIs.  Please
> provide some editorial construct to suggest that practically any kind of
> targeted ads are going to entail some trade in privacy, and explain the risks
> specifically or with a reference.

**Comment by GrumpyOldTroll** [comment]
We think the points to make are:
- media operators, your media is part of an arms race aiming to track users for more effective advertisers
- There are some efforts, such as [Topics](https://github.com/patcg-individual-drafts/topics), to get the ecosystem to reduce its reliance on individual tracking while still achieving targeted ads, which are worth a lot of money (pick out a reference or 2 from e.g. [1] https://www2012.universite-lyon.fr/proceedings/proceedings/p111.pdf )

As an initial idea, we're thinking perhaps to add a paragraph after the first mention of targeting, and we're wondering if this is in the right direction, and whether you can suggest any specific improvements?:
https://htmlpreview.github.io/?https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/blob/gh-pages/draft-ietf-mops-streaming-opcons.html#section-5.4-5:

Traditionally, targeted ads have relied on user tracking, which involves a relatively large privacy exposure for end users.  At the time of this writing some proposals such as [Topics](https://github.com/patcg-individual-drafts/topics) have been made in an effort to reduce that exposure without losing the effects of targeting (ref from [1] that measures a high impact).

We found a few references touching on the risks, like:
- https://www.makeuseof.com/tag/targeted-ads-threat-privacy/
- https://getterms.io/blog/the-risks-of-targeted-advertising/

But maybe you know a better reference?

**Comment by evyncke** [comment]
Just wondering when we could expect some PR to address Roman's DISCUSS.

**Comment by SpencerDawkins** [comment]
Hi, @evyncke, Jake had asked @@rdanyliw for guidance [here](https://mailarchive.ietf.org/arch/msg/mops/jwJHVE6kfYtvdatO_dw2_xG6zgk/), the Wednesday before this document was on the telechat. I haven't seen a response yet. 

The authors are meeting later today to coordinate our continued comment resolution, so we may be smarter after that.

**Comment by GrumpyOldTroll** [comment]
https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/pull/168 is my first attempt to address this, please let me know what you think @evyncke and @rdanyliw.
