### ISSUE TITLE
John Scudder's ballot comments

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#157]
> 1. In the Introduction, “a continuous media” makes me sad because of the
> disagreement in number. I get that this may reflect common usage but it still
> made me wince. The obvious way to make it conventionally grammatical would be
> “a continuous media stream” but I suppose that would make the definition
> recursive. :-( So, I don’t have a good solution to offer but maybe you do; if
> so that’d be nice.
> 
> 2. Introduction, “match to client's consumption rate” should be “match the
> client's consumption rate”.
> 
> 3. In Section 3.6, “Bittorrent favored peers
>    who uploaded as much as they downloaded, so that new Bittorrent users
>    had an incentive to significantly increase their upstream bandwidth
>    utilization.”
> 
> I think you don’t mean “so that”, but just “so” — the implied causal arrow is
> reversed by the “that”, you mean something like “therefore”, right?
> 
> 4. In 3.7 you seem to have a stray close brace? “}”
> 
> 5. In 3.7 you misspelled Craig Labovitz’s name as “Labowitz”. The "v" spelling
> is correct.
> 
> 6. Section 5.5.3, s/detction/detection/
> 
> 7. Section 6.1, s/tansport/transport/
> 
> 8. Section 6.1, “approaches like the above generally
>    experiences”, should be “generally experience” (agreement in number).
> 
> 9. Section 7, “prevent media steam manipulation” should be “stream”.
> 
> 10. Section 7.2 has
> 
>    The choice of whether to involve intermediaries sometimes requires
>    careful consideration.  As an example, when ABR manifests were
>    commonly sent unencrypted some networks would modify manifests during
>    peak hours by removing high-bitrate renditions in order to prevent
>    players from choosing those renditions, thus reducing the overall
>    bandwidth consumed for delivering these media streams and thereby
>    improving the network load and the user experience for their
>    customers.  Now that ubiquitous encryption typically prevents this
>    kind of modification, in order to maintain the same level of network
>    health and user experience across networks whose users would have
>    benefitted from this intervention a media streaming operator
>    sometimes needs to choose between adding intermediaries who are
>    authorized to change the manifests or adding significant extra
>    complexity to their service.
> 
> It wasn’t immediately obvious to me as a reader what recourse (other than
> intermediaries) the media streaming operator would have, regardless of their
> willingness to add extra complexity.
> 
> - Are you implicitly referencing something you’ve touched on elsewhere in the
> document (an xref would be nice if so),
> 
> - or are such “extra complexity” solutions known and published (again, a ref
> would be nice),
> 
> - or known but proprietary special sauce (maybe there’s nothing to be done,
> although a few words indicating this might be suitable),
> 
> - or are you just speculating on the basis that as the saying goes, with enough
> thrust, even a brick can fly?

**Comment by SpencerDawkins** [comment]
@GrumpyOldTroll and @acbegen - Most of John's comments are nits and easy to resolve, but there are two that need thought. 

First, this comment

> In the Introduction, “a continuous media” makes me sad because of the
> disagreement in number. I get that this may reflect common usage but it still
> made me wince. The obvious way to make it conventionally grammatical would be
> “a continuous media stream” but I suppose that would make the definition
> recursive. :-( So, I don’t have a good solution to offer but maybe you do; if
> so that’d be nice.

So, let's think about this. We're looking at two, related statements,

>   *  Streaming is **transmission of a continuous media** from a server to a
>       client and its simultaneous consumption by the client.

I'm wondering if it is correct to say 

  *  Streaming is **continuous transmission of media** from a server to a
      client and its simultaneous consumption by the client.

I'll make that change, and see if anyone objects. 

Second, this comment

> 10. Section 7.2 has
> 
> The choice of whether to involve intermediaries sometimes requires
> careful consideration. As an example, when ABR manifests were
> commonly sent unencrypted some networks would modify manifests during
> peak hours by removing high-bitrate renditions in order to prevent
> players from choosing those renditions, thus reducing the overall
> bandwidth consumed for delivering these media streams and thereby
> improving the network load and the user experience for their
> customers. Now that ubiquitous encryption typically prevents this
> kind of modification, in order to maintain the same level of network
> health and user experience across networks whose users would have
> benefitted from this intervention a media streaming operator
> sometimes needs to choose between adding intermediaries who are
> authorized to change the manifests or adding significant extra
> complexity to their service.
> 
> It wasn’t immediately obvious to me as a reader what recourse (other than
> intermediaries) the media streaming operator would have, regardless of their
> willingness to add extra complexity.

(followed by some excellent guesses about recourse)

I read this text as saying that your streaming service is less complex if you have an intermediary that is modifying manifests during peak hours, than if you add that functionality to media servers that are already complex, especially if intermediaries are making a few well-understood changes to the manifests that only need to work for media players downstream on a given path, while a media server would have to maintain multiple versions of the manifests that that, in total, cover every possible modification that any intermediary would have done, and **then** figure out how to send each media player the appropriate version of the manifest for that media player. 

If that's what other people think, we can say that. If it's not what other people think, we need to talk.

**Comment by GrumpyOldTroll** [comment]
The first one works for me ("Streaming is a continuous transmission of media").

For the second, yes, that was my intent.  It is possible to deliver different manifests to different clients.  Doing so based on some kind of aggregated estimate of the path load (possibly including peak hours/time of day, etc.) can do roughly the same job of reducing network load that was previously done with on-path edits to unencrypted manifests, but it adds a lot of complexity to the media service, which was previously instead taken on by (some of) the networks with a problem.
