### ISSUE TITLE
Better quantification of number of users served

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#180]
From @ncamwing -

> -       Section 4.1: better quantification of the number of users it can serve is needed
> as better guidance (vs. “…do not need to scale to more than a few users at a time”)
> As I can see live media events (like conference calls?) where there could be up to
> a hundred users (whether recommended or not!) attempting to hold a collaborative
> conversation (e.g. live video, audio and other resources like whiteboarding)

**Comment by acbegen** [comment]
Well, "a few users" should not be read literally in this context. Surely, there can be many users when serving a latency under a second, but the scale is orders of magnitude different than other live streaming scenarios (10-100s vs. millions). Maybe we can revise the text as follows:

s/Worth noting is that many applications for ultra-low-latency delivery do not need to scale to more than a few users at a time, which simplifies many delivery considerations relative to other use cases.
/Worth noting is that many applications for ultra-low-latency delivery do not need to scale to as many users as the low-latency and non-low-latency live delivery, which simplifies many delivery considerations relative to other use cases.
