### ISSUE TITLE
Section 5.4 - better description of privacy (and security) violations

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#181]
From @ncamwing -

> -       Section 5.4 2nd paragraph pg. 20 speaks to potential privacy (and security)
> violations as ad fraud.  As a non-expert in the full live-streaming workflow with ads
> but a security expert, a better description of the current workflow or mention that the
> misreporting is out of scope (?) is needed.  If the intent is to provide guidance for future
> design and protocol improvements, at least a reference to how current solutions work
> and fail is required.

**Comment by SpencerDawkins** [comment]
To @ncamwing - we had gotten comments about this topic from other reviewers, both inside and outside the IESG. I'm also a non-expert on the full workflow of live streaming, but I THINK the -11 version of Section 5.4 may address your comments. 

Could you check[ the diff](https://www.ietf.org/rfcdiff?url2=draft-ietf-mops-streaming-opcons-11.txt), and see what you think?

**Comment by ncamwing** [comment]
The restructuring and addition to the privacy considerations are a definite improvement.  Thanks for addressing!

**Comment by SpencerDawkins** [comment]
@ncamwing - oh, thank you! 	:sweat_smile:
