### ISSUE TITLE
Git repo reference

### ISSUE THREAD

**Issue by ldaigle** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#19]
Needs updating in  Section 1.1:
  "This document is in the Github repository at
   https://github.com/GrumpyOldTroll/ietf-mops-drafts.  Readers are
   welcome to open issues and send pull requests for this document."
to:
 This document is in the Github repository at
   https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons.  Readers are
   welcome to open issues and send pull requests for this document.

**Comment by GrumpyOldTroll** [comment]
Fixed by https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/commit/0c1a7dd704a0b807eac50f2c88a05cc78670df74
