### ISSUE TITLE
section 3.2.1

### ISSUE THREAD

**Issue by acbegen** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#2]
It says: 
      TCP Slow-start when restarting after idle requires multiple RTTs
      to re-establish a throughput at the network's available capacity.
      On high-RTT paths or with small enough segments, this can produce
      a falsely low application-visible measurement of the available
      network capacity.

Well, TCP slow-start restart happens when TCP stays idle long enough. "Long enough" is a factor for RTT, so I don't think slow-start restart is more likely when RTT is higher. When the segments are small, it is not more likely, either. I think what we are looking for is when the "on" duration is substantially longer than the "off" duration in the HTTP transaction. And that means, when the segment download time is substantially shorter than the inter-request time (typically the segment duration), which implies download speed is far greater than the segment's encoding bitrate. In that case, SSR will likely happen.

**Comment by GrumpyOldTroll** [comment]
Yes, good point, thanks, the main thing is the amount of idle time.  Maybe a reference to RFC 7661 is also in order, as a mitigation for senders who expect this.  Not sure if the default behavior for common server systems should get a mention here as well (and also maybe stuff like linux's net.ipv4.tcp_slow_start_after_idle).

**Comment by acbegen** [comment]
7661 could be mentioned as a note. I have seen some servers disabling SSR while others leaving it on by default.

**Comment by acbegen** [comment]
Linked to #54 (which is already addressed adequately IMO, so we can close this issue).

**Comment by SpencerDawkins** [comment]
Fixed in #59.
