### ISSUE TITLE
readme: consider adding links to I-D and editor's copies

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#21]
It would be helpful to have some links to the latest draft version of the I-D in readme.

Please also consider adding one for the cutting-edge editors copy reflecting head of master. This can be hosted on gh-pages and either updated manually or automatically via a Continuous Integration job.

**Comment by GrumpyOldTroll** [comment]
Added these links in https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/commit/5c57f57b9c0d3b18668688e2cb66b33d6d7ad87c

However, the actual contents of the "editor's copies" seems currently broken due to https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/issues/25.
