### ISSUE TITLE
Discussion on contention and/or fairness in the network

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#22]
Since the intro says 

> This document aims to provide a taxonomy of networking issues as they
   relate to quality of experience in internet video delivery.

I'm a little surprised to not see anything about the effects on video QoE caused by contention in the network, or the role that fairness between other flows and/or protocols plays on video and other applications.

Finally, its been interesting to see how large content providers have reduced streaming bitrates in response to large-scale contention during the COVID pandemic, whether voluntarily or via external pressures. This is especially curious when content is distributed via ABR technologies which should accommodate switching to lower bitrates. (I've heard anecdotal reasoning that the detection of contention is too slow, but unsure if that is really true).

**Comment by acbegen** [comment]
> Finally, its been interesting to see how large content providers have reduced streaming bitrates in response to large-scale contention during the COVID pandemic, whether voluntarily or via external pressures. This is especially curious when content is distributed via ABR technologies which should accommodate switching to lower bitrates. (I've heard anecdotal reasoning that the detection of contention is too slow, but unsure if that is really true).

One of the more logical explanations of the situation I have I read:
https://newsroom.bt.com/the-facts-about-our-network-and-coronavirus/
EU asking Netflix to drop the bitrates was a total BS IMO.

**Comment by murillo128** [comment]
It is worth noting that some protocols rely on the transport layer bwe/cc (the ones that are TCP based) while others have to implement their own mechanisms (udp based like QUIC or RTP).

In that regard, I would differentiate the loss based bwe/cc algorithms (TCP, new Reno, bbr) vs the delay based ones (copa).

**Comment by SpencerDawkins** [comment]
I'm planning to focus a PR for this issue on fairness and contention, but defer to the "Extremely Unpredictable Usage Profiles" section, which we've recently merged into Master, for anything about CoViD-19-related impacts on network performance for streaming media. 

Please let me know if that's not a good plan.

**Comment by SpencerDawkins** [comment]
OK, I'm about 10 commits (it seemed like more) into the PR for this issue, and am now thinking that I should divide what is now the "Evolution of Transport Protocols and Transport Protocol  Behaviors" section into a UDP/TCP section that comes before the ABR section, because those are the protocols that people use with ABR today, and a QUIC section (that is actually "evolution") that remains after the ABR section. @GrumpyOldTroll and @acbegen, do you have any thoughts about that?

I'm pretty sure it would allow us to tighten up the discussion of interaction between ABR and transport protocol behavior in the ABR section.

**Comment by GrumpyOldTroll** [comment]
Sounds reasonable to me, I think.

**Comment by SpencerDawkins** [comment]
I'll make that split (and see if I can do that without conflicts - I think I'm only moving text in #35, so should be easy.
