### ISSUE TITLE
historical charts of usage patterns with references

### ISSUE THREAD

**Issue by GrumpyOldTroll** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#26]
I don't remember where this suggestion came from, but it was on the list in the 107 interim slides, so I figured it should be tracked:
https://www.ietf.org/proceedings/interim-2020-mops-01/slides/slides-interim-2020-mops-01-sessa-update-on-draft-ietf-mops-streaming-opcons-01.pdf#page=4

**Comment by acbegen** [comment]
Maybe refer to Cisco VNI? https://www.cisco.com/c/en/us/solutions/service-provider/visual-networking-index-vni/vni-forecast.html

**Comment by SpencerDawkins** [comment]
Cisco VNI link is already a 404, so ... 

Checking with RFC Editor to see whether they can handle SVG yet.

**Comment by GrumpyOldTroll** [comment]
The point of this is trying to show internet scale growth of video traffic over time, both by proportion and by gross volume, not really about including pictures.

This maybe is already covered by our intro paragraph:

"Estimates put the total share of internet video traffic at 75% in 2019, expected to grow to 82% by 2022. This estimate projects the gross volume of video traffic will more than double during this time, based on a compound annual growth rate continuing at 34% (from Appendix D of [CVNI])."

We should consider just closing this issue.

**Comment by GrumpyOldTroll** [comment]
Related point (perhaps a new issue?):  this info may stop being available--prior reports often came from DPI at IXPs or similar to monitor traffic, but since the dawn of ubiquitous encryption this info will stop being available, and we'll (probably?) only have reports from servers.

**Comment by SpencerDawkins** [comment]
We're thinking this is Won't Fix - at a minimum, this isn't information we can update in the future.

**Comment by GrumpyOldTroll** [comment]
Pulled these out of the text of the draft as part of this issue, from the bottom of section "2.4 Predictable Usage Profiles":

TBD: insert charts showing historical relative data usage patterns with error bars by time of day in consumer networks?

TBD: Cross-ref vs. video quality by time of day in practice for some case study? Not sure if there's a good way to capture a generalized insight here, but it seems worth making the point that demand projections can be used to help with e.g. power consumption with routing architectures that provide for modular scalability.
