### ISSUE TITLE
Normalize the whitespace/line wrap strategy

### ISSUE THREAD

**Issue by GrumpyOldTroll** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#29]
@squarooticus had what I think is an excellent suggestion of one line per sentence:
https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/pull/27#discussion_r513580921

I've seen other docs use one line per paragraph, which I attempted to use in a recent commit but I kind of hate.

Regardless, we should make a whitespace-only pass through the doc and make it all the same.  I vote for one line per sentence.  (I assume this would not include text inside bullet points and tables--not sure if there's a section of a doc somewhere about the pros and cons of different approaches?)

**Comment by englishm-llnw** [comment]
I'm happy to make a formatting pass and check what kramdown, etc. does with it.

Do we want to land the changes in https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/pull/27 first, or reformat first and rebase your PR?

**Comment by GrumpyOldTroll** [comment]
I guess I'm voting for land the changes first and do a whitespace format when we won't have conflicts.  Should be pretty quick, right?

**Comment by GrumpyOldTroll** [comment]
(*note, there is another pull request also that would be affected if we do it now: https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/pull/30 )
