### ISSUE TITLE
Low-latency vs. others

### ISSUE THREAD

**Issue by acbegen** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#3]
I think this draft deserves a separate section that will explain what streaming is and what latency is. Then a classification of based on the latency requirements is in order. 
1) low latency live (glass-to-glass latency should be < 10s, to compete with broadcast)
2) non-low-latency live (still live but latency can be > 10s)
3) on-demand (where latency is not a concern, but startup delay is)

Then topics like inter-destination (or inter-player) synchronization becomes important. Your dash stream vs. the broadcast or the twitter feed. They need to be more or less close to each other in the time domain as otherwise it will look bad.

**Comment by GrumpyOldTroll** [comment]
+1, this sounds like a valuable section to me.  Especially if there's references for the numbers involved in the requirements.

**Comment by acbegen** [comment]
I can take a crack at this as well.

**Comment by agouaillard-cosmo** [comment]
I think you need to make a real-time section (<1s), to separate the technologies that are not http-based nor file-based. We could put there RTMP, RTSP 2.0, WebRTC and globally all kinds of RTP-based streaming techs. There is an emergence of use cases that require that, and teh slides from Justin Uberti during MOPS@IETF 105 about Stadia is a good example. (https://datatracker.ietf.org/meeting/105/materials/minutes-105-mops-00). Some people use "interactive streaming" to refer to it. Stadia is aiming for 150ms latency.

**Comment by acbegen** [comment]
Well, to be accurate, all the three I listed are real-time streaming as well. If they were not, they would be download-and-watch type of stuff. What you are getting at is interactive and if we think gaming streaming type of stuff is within scope, yes we should add that, too.

**Comment by SpencerDawkins** [comment]
Leslie Daigle was pretty clear that MOPS wasn't chartered for guidance about WebRTC in an email exchange about a month ago. We should definitely confirm whether interactive applications are in scope with the chairs before moving forward on this issue.

**Comment by agouaillard-cosmo** [comment]
I think checking with the chair is reasonable. Now, please note that this comment was not specific to webrtc, and included two other example protocols. SRT would also fit in this bucket as well.

**Comment by SpencerDawkins** [comment]
My apologies, I mis-typed. Leslie's reference was to "realtime comms" being out of scope when MOPS chartered. I hadn't realized that, so was talking with her and with Eric, the responsible AD about WebRTC, but the statement was broader than WebRTC.

**Comment by agouaillard-cosmo** [comment]
Ok, so what is the latency threshold at which you consider a technology not suitable for inclusion in mops scope? Shall we directly disqualify SRT for being real-time? I was under the impression that feedback on SRT for example was welcome by the group. I apologise for joining late, and I have not read the specific e-mail you mentioned. Would you mind to kindly point me to it?

**Comment by squarooticus** [comment]
Please move further discussion of this issue to the mailing list before merging any related PRs.

**Comment by GrumpyOldTroll** [comment]
For easier reference, mailing list discussion is here:
https://mailarchive.ietf.org/arch/msg/mops/8Q4D62Arg871YJ1BdYaILcPoAWM/

**Comment by SpencerDawkins** [comment]
Don't want to fight over exact descriptions and timings here - naming applications for different categories as examples. Giving general characteristics of those applications would be useful. Streaming Video Alliance has some categories. Overlapping categories seem to be fine. 

If we can include stable references, that's likely useful. 

Ali will do a PR for this.

**Comment by SpencerDawkins** [comment]
Fixed in #59.
