### ISSUE TITLE
Add section on ads?

### ISSUE THREAD

**Issue by GrumpyOldTroll** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#31]
Advertising is an important part of the video delivery landscape and has an impact on network design and operational considerations in streaming video, for sure.

@mattstock gave a pull request that's a decent start here:
https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/pull/18

There are some unanswered comments in that pull request, but we should consider adding such a section and refining it even in the absence of responses.

**Comment by acbegen** [comment]
Ads are evil :) Could the IETF ban them?

**Comment by SpencerDawkins** [comment]
@SpencerDawkins will review proposed text in PR
