### ISSUE TITLE
Section 2.1.1 Video bit rates table 

### ISSUE THREAD

**Issue by gitnnelg** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#40]
Somehow I missed this until now- the issue is the representative bit rates in Table 1 are far too high and do not match the actual bit rate ladders that are being used to stream video in production currently.

Curren in the doc, which I believe is based on old encoding rates is:

Name | Width x Height | Typical | Peak

DVD | 720 x 480 | 1.3 Mbps | 3 Mbps
720p (1K) | 1280 x 720 | 3.6 Mbps | 5 Mbps
1080p (2K) | 1920 x 1080 | 8.1 Mbps | 18 Mbps
2160p (4k) | 3840 x 2160 | 32 Mbps | 70 Mbps

For example - Netflix in a blog (https://netflixtechblog.com/optimized-shot-based-encodes-for-4k-now-streaming-47b516b10bbb)  published in Aug of 2020 argues that high quality video can be done at much lower bitrates for 4K video , but their graphs also show other resolutions. 

In the cited experiments they had 4K video bitrates ranging from 8 Mbps down to 1.7Mbps with an average being 3.2 Mbps. 

Certainly 1080p at 1Mbps is quite commonly seen in the wild.  

Perhaps @acbegen can reach into his academic citations and pull out a better bitrate ladder that represents actual delivery rates being used.

**Comment by SpencerDawkins** [comment]
We need to find numbers that we can actually publish.

**Comment by SpencerDawkins** [comment]
@acbegen is checking for a better reference :-)

Need to think about whether we can/should distinguish between codecs in this material.

**Comment by SpencerDawkins** [comment]
Fixed in #59.
