### ISSUE TITLE
Update to caching systems

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#53]
From Will - 

2.3 Caching Systems

May be worth mentioning that concurrent gaming downloads nowadays drive larger traffic peaks than live or VOD streams.

Additionally, something missing from this section is the impact of chunk transfer of aggregating responses. These are being used increasingly for low latency delivery. The caching system is receiving the object in real-time while simultaneously forwarding it to the client. The object size is not known until the transmission is complete. Much of caching infrastructure failover and redundancy is predicated on knowing the size of the object you are transmitting. Distribution tiers have a hard time separating a gap in data from a failure of an upstream component. Setting appropriate time-outs becomes problematic.

**Comment by GrumpyOldTroll** [comment]
> May be worth mentioning that concurrent gaming downloads nowadays drive larger traffic peaks than live or VOD streams.

This is a true and fine point, but I'm not sure it needs mention in a video-centric doc, except maybe how this impacts video delivery from the shared resources, but I think the congestion control sort of takes that.  I'll give it some thought, but I don't think it's really specific to caching or what we get out of raising it here, so I'm leaning toward not doing anything in this section on this point.

**Comment by GrumpyOldTroll** [comment]
I'll follow up with a separate question about the other half of this comment, I'm not quite sure what it's saying.  But it's a good point that talking about some non-intuitive failure modes might be handy here.

**Comment by SpencerDawkins** [comment]
Hi, @GrumpyOldTroll - any update here?

**Comment by GrumpyOldTroll** [comment]
Not yet.  I did send a message hoping to learn enough about the failure modes and what you can do about them to write something meaningful here, but there are some vacation-related delays and once people are back I may have to ping again.
