### ISSUE TITLE
Refactoring Adaptive Segmented Delivery subsections to focus on reasons why signals are lower or higher than they should be

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#67]
The editors are 2:1 in favor of dropping ECN. Spencer is graciously in the rough. 

We should be talking more broadly about what happens when you lose *any* packets, 

If ECN belongs in the draft, it belongs somewhere else. 

"Coming improvements in transport behaviors" more broadly - we're talking about BBR and about end-to-end transport encryption now. Maybe we should talk about things like edge computing, etc ... but @GrumpyOldTroll will talk to the working group about this before we start a major refactor.

**Comment by GrumpyOldTroll** [comment]
The point of these sections (4.3.1 Idle Time Between Segments and 4.3.2 Head of Line Blocking) was to explain how and why your bandwidth measurements can go wrong when you're trying to do ABR things with your bandwidth measurements.

By name this seems like perhaps a better fit in the 4.4 Measurement Collection section, there might be a reason to merge some of the discussion there or reorganize the 2 sections together.

**Comment by GrumpyOldTroll** [comment]
We maybe should also add a section along these lines on the wide variability in bitrates as things move, both for wi-fi and LTE and 5g.

**Comment by GrumpyOldTroll** [comment]
Note also: "Refactor" here means provide a coherent story for why your ABR measurements can go wrong and what you can do about it.
