### ISSUE TITLE
This document isn't a taxonomy any more, is it? I think this may be left over from Jake's individual draft

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#69]
We should probably talk about how to update 

   This document aims to provide a taxonomy of networking issues as they
   relate to quality of experience in internet video delivery.  The
   focus is on capturing characteristics of video delivery that have
   surprised network designers or transport experts without specific
   video expertise, since these highlight key differences between common
   assumptions in existing networking documents and observations of
   video delivery issues in practice.

@SpencerDawkins might suggest this (but didn't put it in -05):

   This document 
   focuses is on capturing characteristics of video delivery that have
   surprised network designers or transport experts without specific
   video expertise, since these highlight key differences between common
   assumptions in existing networking documents and observations of
   video delivery issues in practice.

Thoughts from @GrumpyOldTroll or @acbegen?

**Comment by GrumpyOldTroll** [comment]
Sure, that works for me.
