### ISSUE TITLE
Expansion and references for Table 1

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#71]
@acbegen - could you provide the appropriate references for AVC and HEVC, and an expansion for DVD, included in Table 1? I can make the change if you can provide the information.

**Comment by SpencerDawkins** [comment]
Hi, @acbegen, could you take a look at this? I can guess, but I'd be guessing ... thanks!

**Comment by SpencerDawkins** [comment]
Hi, @acbegen, my understanding is that in Table 1, 

- AVC could be referenced as  H.264 or MPEG-4 Part 10, Advanced Video Coding (MPEG-4 AVC)
- HEVC could be referenced as High Efficiency Video Coding (HEVC), also known as H.265 and MPEG-H Part 2

and "DVD" just means "DVD, as in popular use, so no expansion necessary". Does that sound about right? If so, I can just add this to the text under Table 1, and to the references.

**Comment by acbegen** [comment]
Hi Spencer, yes, there are multiple names for the same codecs, we dont need to spell out each IMO but should use the same "class" (AVC + HEVC not AVC + H.265). I am fine with either class. And DVD should be known but if you need it is Digital Video Disc.

The main reference for Table 1 is mostly the [Encodings]. The tables there are a bit more involved, so I improvised a bit to simplify the table. Would that be ok?

**Comment by SpencerDawkins** [comment]
Hi, @acbegen, that all sounds good. Is there a preferred reference that I could include for HEVC and AVC (to use that form of the names)?

**Comment by acbegen** [comment]
Would this work? https://www.mpegstandards.org/standards/

**Comment by SpencerDawkins** [comment]
After thinking a bit more about this (thanks, @acbegen), I'm leaning toward just using H.264 and H.265, and letting someone ask about references if they need them. The IETF has been referencing H.26x codecs for a REALLY long time, so this shouldn't cause much confusion, I think. I'll do a PR for this.

**Comment by SpencerDawkins** [comment]
The PR for this is having problems with CircleCI. I'm not going to merge this until we figure out what the problem is. I've asked @squarooticus for clues via email about this.
