### ISSUE TITLE
Section on consequences of poor bitrate choice?

### ISSUE THREAD

**Issue by GrumpyOldTroll** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#77]
Maybe another section in 4.3 Adaptive Segmented Delivery.  Discuss consequences of poor choice of bitrate, both high and low. (point was raised that picking high can also cause bufferbloat observed at up to 10s in LTE networks--worth mentioning somehow?)

**Comment by acbegen** [comment]
We should call this section "?hit Happens" because it does.

**Comment by SpencerDawkins** [comment]
I agree with @acbegen on the characterization, but despair somewhat of getting that through AD Evaluation, IETF Last Call, IESG Evalution, and the RFC Editor. 

I offer "Why Making Good Choices Is Hard (And Why That's Not Your Fault)", as a friendly amendment ;-)

**Comment by acbegen** [comment]
If with a reference to https://forrestgump.fandom.com/wiki/Shit_happens, I am fine :)

**Comment by acbegen** [comment]
This is now addressed in the reading list section. Issue can be closed.

**Comment by SpencerDawkins** [comment]
@acbegen, I believe you, but I'm not seeing anything in the reading list section contents that obviously addresses this topic. Am I missing it, or is that something you're planning to add?

**Comment by acbegen** [comment]
The ABR survey paper is a good resource on that and has pointers to many related papers.

**Comment by SpencerDawkins** [comment]
@acbegen, like I said, I believed you :-) What I meant, by my question, is whether anyone would know to look in papers under ABR for that information. Maybe we should have a quick discussion (on the next editor call?) on the section titles in the document, to make sure they are helpful to the intended readers, in addition to being accurate?

**Comment by acbegen** [comment]
> @acbegen, like I said, I believed you :-) What I meant, by my question, is whether anyone would know to look in papers under ABR for that information. Maybe we should have a quick discussion (on the next editor call?) on the section titles in the document, to make sure they are helpful to the intended readers, in addition to being accurate?

I provided one sentence to each section - not paper - to help the reader. I suppose if one is indeed interested in finding out the best reference for a specific problem, he/she can start from this list and find the target reference rather quickly. Would that work?

**Comment by SpencerDawkins** [comment]
@acbegen - that's perfect. Do you need any help putting together the draft text that will point to this (and explain why it's OK to handle the additional reading section this way, so the document shepherd will have an explanation to cut and paste into the shepherd write-up?)

**Comment by acbegen** [comment]
> @acbegen - that's perfect. Do you need any help putting together the draft text that will point to this (and explain why it's OK to handle the additional reading section this way, so the document shepherd will have an explanation to cut and paste into the shepherd write-up?)

Certainly Spencer. Please provide the necessary text. Thanks.

**Comment by SpencerDawkins** [comment]
@ldaigle and @squarooticus - the plan is that this draft will have a "living section pointing to further reading", that would be maintained by the working group. I anticipate that you may want to hang onto a paragraph that looks something like this, to include in WGLC announcements and in the https://datatracker.ietf.org/doc/draft-ietf-mops-streaming-opcons/ Shepherd Write-up. 

This issue is complete (in our opinion), but I've tagged it with the "documentation" label, and I'll leave this issue open until you have a chance to comment on the proposed text, or otherwise grab it for chair use as appropriate. 

> _**Note: (currently section 7) "Further Reading and References", is intended to be maintained as a useful resource for streaming operators in understanding relevant technologies, especially as they evolve over time. For this reason, the plan is that the contents of this section will be copied to a non-archival web resource (likely as an IETF-owned wiki) at AUTH48 time, so that this section in the published RFC will match the non-archival web resource on the day of publication.**_ 

If anyone kidnaps you demanding to know what the plan is for maintenance, I'd suggest "the MOPS working group will maintain the non-archival resource as updates are needed", but I'd wait for someone to ask the question before saying that out loud. 

Do The Right Thing, of Course.

**Comment by squarooticus** [comment]
> If anyone kidnaps you demanding to know what the plan is for maintenance, I'd suggest "the MOPS working group will maintain the non-archival resource as updates are needed", but I'd wait for someone to ask the question before saying that out loud.

I think this sounds reasonable, but if I can't speak freely I'll blink to the chorus rhythm of Never Gonna Give You Up.

**Comment by SpencerDawkins** [comment]
@squarooticus, I knew I could count on you ... I'll close this now, and assume that you and @ldaigle can find the note if you need it for WGLC/shepherd write-up.
