### ISSUE TITLE
Segment size and keyframe intervals

### ISSUE THREAD

**Issue by GrumpyOldTroll** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#86]
Describe in general terms segments and frame types, tradeoffs associated with segment size and keyframe interval selection. (related to idle-time and caching)

Thanks @englishm-ietf for the suggestion as part of https://github.com/ietf-wg-mops/draft-ietf-mops-streaming-opcons/pull/85

**Comment by SpencerDawkins** [comment]
This is about low-latency and where you can start rendering in a media stream. 

Mention and explain briefly? This isn't quite about the NETWORK, but it's about caching, which is probably in the network. 

Keyframes can also be used for thumbnails when you hover over something. 

More keyframes gives you more flexibility in where you can start rendering, but is also larger and comes with a bandwidth and path occupancy cost.

**Comment by SpencerDawkins** [comment]
Insert this material in "For further reading" (#14}?

**Comment by acbegen** [comment]
This is now addressed in the reading list section. Issue can be closed.

**Comment by englishm-ietf** [comment]
My thought here was that stream characteristics like GOP sizing place a constraint on switching opportunities for renditions (ABR) and ad insertion, which can have an impact on bandwidth utilization, etc. I thought some explanatory text might help pull those sections together a bit more, but I'm fine with it just being covered in the further reading, too.

**Comment by acbegen** [comment]
> My thought here was that stream characteristics like GOP sizing place a constraint on switching opportunities for renditions (ABR) and ad insertion, which can have an impact on bandwidth utilization, etc. I thought some explanatory text might help pull those sections together a bit more, but I'm fine with it just being covered in the further reading, too.

It is not very easy to correctly discuss the trade-offs between the key frame internal, segment size, encoding quality, impact on the storage, request rate and all that. There are detailed studies that do an excellent job on explaining these trade-offs, so referring the readers to these studies is better IMO.

**Comment by acbegen** [comment]
Closing this issue as the further reading section identifies the relevant studies.
