### ISSUE TITLE
Clearer definition of "continuous"/"simultaneous" in section 1.

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-mops/draft-ietf-mops-streaming-opcons#98]
From @evyncke 
We like the terms, but need to clarify this.

**Comment by GrumpyOldTroll** [comment]
Current text:
- Streaming is transmission of a continuous media from a server to a client and its simultaneous consumption by the client.
- Here, "continuous media" refers to media and associated streams such as video, audio, metadata, etc. In this definition, the critical term is "simultaneous", as it is not considered streaming if one downloads a video file and plays it after the download is completed, which would be called download-and-play.

Notes:
- we think "simultaneous" is a decent word here in that the receiver is rendering at the same time the stream is being encoded (and that e.g. "concurrent" would not be a helpful substitution to clarify the point).  So we think Eric's comment is asking for clarification that there is a latency gap.  (This seems maybe sufficiently clarified later in the text where we talk about the glass to glass latency, but maybe there's a way to phrase this up front without adding confusion?)

**Comment by acbegen** [comment]
> * we think "simultaneous" is a decent word here in that the receiver is rendering at the same time the stream is being encoded (and that e.g. "concurrent" would not be a helpful substitution to clarify the point).  So we think Eric's comment is asking for clarification that there is a latency gap.  (This seems maybe sufficiently clarified later in the text where we talk about the glass to glass latency, but maybe there's a way to phrase this up front without adding confusion?)

While I am not a native speaker, I could not find a better word than "simultaneous" here. It emphasizes that the transmission/delivery/reception of the media data and consumption of it have to be more or less at the same time. I prefer not to use "latency" here as our definition also applies to on-demand streaming (where latency is infinite). But obviously based on the playback buffer size, there will be a delay between the reception of the media and its consumption.

**Comment by squarooticus** [comment]
Isn't "progressive" the term of art for this kind of download?

**Comment by GrumpyOldTroll** [comment]
I don't think so.  Progressive in an image or video context usually means that extra data adds enhancement layers that increase the detail.  I don't see the term used terribly often, but when I do that's what I've seen. (See e.g. https://docs.microsoft.com/en-us/windows-hardware/drivers/display/mpeg-and-progressive-content)

The other way I've seen it used is that the p in 1080p stands for progressive (as opposed to interlaced), but this refers to the screen-drawing pixel progression--also unrelated to glass-to-glass latency.  See e.g. https://www.youtube.com/watch?v=7v_85PMAm44.

So afaict "progressive" wouldn't help here.

**Comment by GrumpyOldTroll** [comment]
(PS: In that first sense, for still images they call the concept "progressive" when websites do it that way but for streaming video it's usually called scalable coding.)

**Comment by squarooticus** [comment]
Ah, ok. At best it's got too many meanings to be a good candidate.

**Comment by squarooticus** [comment]
Why isn't "concurrent" a better word? "Simultaneous" in this context seems like it implies the same thing happening in two places (which in turn implies very low latency), while "concurrent" encoding/playback to my mind means they are both on-going but independent. I refer you to the (maybe historical) term "concurrent programming" for an analogy.

**Comment by GrumpyOldTroll** [comment]
We thought "concurrent" was neither better nor worse.  It has what seems like the same problem to the same degree.

**Comment by squarooticus** [comment]
I think concurrent is strictly better. So if those are the only two options, I'd go with concurrent.

**Comment by acbegen** [comment]
> I think concurrent is strictly better. So if those are the only two options, I'd go with concurrent.

I can live with "concurrent" (noting that progressive is not the right term here, it has a very particular meaning in streaming). FWIW, "simultaneous" has been used in the literature without an issue for a long time.

**Comment by SpencerDawkins** [comment]
@squarooticus - :face_with_head_bandage: after banging my head against the desk, I think the problem with "simultaneous" is that, in the atomic clock resolution sense, what is happening at the client is **NOT** simultaneous with what is happening at the server. Does that make sense?

I'm looking at our current text again (thanks, @GrumpyOldTroll for jogging my mind with your first comment), where we say this:

> Streaming is transmission of a continuous media from a server to a client and its **simultaneous** consumption by the client.

Is "synchronous" worse? As in 

>Streaming is transmission of a continuous media from a server to a client and its **synchronous** consumption by the client.

And I apologize for poking at this, but 

- @evyncke could reasonably expect that after working on "Operational Considerations for Streaming Media" since July 2019, we would be able to define "streaming", but more seriously, 
- ISTM that we're talking about this in various places within MOQ, so getting a stake in the ground in this document would be helpful for future work, as well. 

Thoughts?

**Comment by acbegen** [comment]
Synchronous refers to things like lip sync. Can't we stick with people have been using for some time? I dont think simultaneous is any worse than other proposals.

**Comment by squarooticus** [comment]
Like I said, if "simultaneous" is actually a widely-employed term of art in this space, then whether or not it's literally ambiguous to a layperson is really beside the point.

**Comment by gitnnelg** [comment]
For what it’s worth, I’ve read the text and simultaneous does seem to be the best word choice at both a technical level and just plain English.

The other terms synchronized and concurrent carry a lot of extended meaning especially in the engineering domain with synchronized requiring some sort of synchronization mechanism and concurrent implying that there is a resource scheduling priority on both sides that ensures that the respective processes don’t get migrated to a swap out state and therefore are prevented from guaranteed real time execution.

If we’re really, really stuck – we could also use the phrase sense like “consumed without delay”, or “viewed co-temporally”, or go with engineering level specification of “viewed within in a window of 0-125s and no deliverable expectation of recording before consumption.

All of which are also far worse than, “simultaneous” in this listeners ear.

-glenn

On 4/13/22, 7:35 AM, "Kyle Rose" ***@***.******@***.***>> wrote:


Like I said, if "simultaneous" is actually a widely-employed term of art in this space, then whether or not it's literally ambiguous to a layperson is really beside the point.

**Comment by SpencerDawkins** [comment]
Hi, @evyncke ... we love you, but we can't come up with a better term, and we have demonstrated that coming up with a **WORSE** term is really easy ...

**Comment by evyncke** [comment]
I love you too :-)

More seriously, the above discussion was interesting but the conclusion is that "better don't touch it", which is perfectly fine for me.
